### ISSUE TITLE
Module not found: Error: Package path ./register is not exported from package /node_modules/cypress-xray-plugin

### ISSUE THREAD

**Issue by caique-rd** [Qytera-Gmbh/cypress-xray-plugin#343]
### Description

Hey @csvtuda how are you? Could you help me with a problem in the latest version of cypress-xray-plugin, please? I was using the v6 version and everything was working, but after I update to 7.0.1 when I try to run cypress in run mode with cypress-xray-plugin I get the following error:

```
Oops...we found an error preparing this test file:

  > cypress/support/e2e.js

The error was:

Error: Webpack Compilation Error
Module not found: Error: Package path ./register is not exported from package /node_modules/cypress-xray-plugin (see exports field in /node_modules/cypress-xray-plugin/package.json)
```

### Cypress version

13.12.0

### Plugin version

7.0.1

### Jira/Xray type

Cloud

### Acknowledgements

- [X] I have made sure not to include any sensitive data in screenshots or obfuscated all occurrences.
- [X] I have made sure not to include any sensitive data in descriptions or replaced all values with placeholders.
- [X] I have made sure not to include any sensitive data in code snippets or replaced all values with placeholders.

**Comment by csvtuda** [comment]
Hi @caique-rd,

the `/register` import does not exist anymore in version 7. It has been replaced with:

```ts
// cypress/support/e2e.js
import "cypress-xray-plugin/commands";

// ...
```

or

```ts
// cypress/support/e2e.js
import "cypress-xray-plugin/commands/tasks";

// ...
```

**But**: Up until version 7, these imports did not do anything, the imported module was [completely empty](https://github.com/Qytera-Gmbh/cypress-xray-plugin/blob/ed6452fd04c7500e35465047841731ce0d408dba/src/register.ts).

From version 7 on, these imports will allow you to upload [`cy.request` data](https://qytera-gmbh.github.io/projects/cypress-xray-plugin/section/guides/uploadRequestData/#upload-request-data) as Xray execution evidence if you wish. If you don't need this, you can simply remove the import line altogether.

**Comment by caique-rd** [comment]
Thank you so much, was exactly this, I forgot to remove the register import, but now it's working as expected.

**Comment by csvtuda** [comment]
To be fair, this change was not documented in the changelog. I must have missed it and will patch it.
